### ISSUE TITLE
`ComplexIntResponse` and `ComplexIntParameter` could be replaced with `big.Int`

### ISSUE THREAD

**Issue by paulhauner** [regcostajr/go-web3#22]
It seems to make more sense to me to replace `ComplexIntResponse` and `ComplexIntParameter` with `big.Int`.

https://github.com/regcostajr/go-web3/blob/55798549017a7e78cee4abc2cea1810e380c3ca1/complex/types/complex-int.go#L39

`big.Int` already has a `Uint64` conversion function to replace the `ComplexIntResponse.ToInt64()` function. With regards to `ComplexIntResponse.ToUint64()`, I can't think of a case where a provider returns a negative number. If we find such a case, it would be from some ancillary method (i.e., not `Call` or `SendTransaction`) and that method should return a type suitable to its purpose (i.e., not a `big.Int`). 

Thoughts?

**Comment by junjchen** [comment]
> big.Int already has a Uint64 conversion function to replace the ComplexIntResponse.ToInt64() function. With regards to ComplexIntResponse.ToUint64(), I can't think of a case where a provider returns a negative number.

think you should swap `ComplexIntResponse.ToInt64()` and `ComplexIntResponse.ToUint64()` in your statement.

+1

**Comment by paulhauner** [comment]
Thanks, it's been so long since I wrote this. I will revisit this and fix this typo.
