### ISSUE TITLE
implementation of getBlockTransactionCountByNumber

### ISSUE THREAD

**Issue by Thebarda** [regcostajr/go-web3#35]
Hello there ! 
Can I create a PR to implement getBlockTransactionCountNyNumber ?

**Comment by junjchen** [comment]
Hi @Thebarda didnt see this earlier but i just did #36

**Comment by Thebarda** [comment]
That's ok :)

**Comment by regcostajr** [comment]
Please, fell free to implement any pending task, issue or new feature, if it's well done, will be accepted and merged.
