### ISSUE TITLE
How to check transaction success or failed by txhash string?

### ISSUE THREAD

**Issue by nifflerfox** [regcostajr/go-web3#37]
Thanks!

**Comment by junjchen** [comment]
You should be able to do so reading the `status` field from [GetTransactionReceipt](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt)

**Comment by regcostajr** [comment]
complementing @junjchen answer:
https://github.com/regcostajr/go-web3/blob/master/eth/eth.go#L573

**Comment by nifflerfox** [comment]
I know that web3 api function `eth_getTransactionReceipt` returns "status"
 
But github.com/regcostajr/go-web3  `GetTransactionReceipt` function doesn't return "status" member.

**Comment by regcostajr** [comment]
Yep, you are right, we need some adjusts to actual implementation, reopening issue.

**Comment by nifflerfox** [comment]
in `ToTransactionReceipt()`  json.Unmarshal returns error in fact

**Comment by tpoxa** [comment]
```
(dto.TransactionReceipt) {
 TransactionHash: (string) (len=66) "0x845f350394068f7fd0ada77c990ddc96258480efbcaf403234189d088bb3fe64",
 TransactionIndex: (int64) 0,
 BlockHash: (string) (len=66) "0x704028464f8342930352caf5d2e2736594781cbceb9b6aceb3e1d83ed319bdd0",
 BlockNumber: (int64) 0,
 CumulativeGasUsed: (int64) 0,
 GasUsed: (int64) 0,
 ContractAddress: (string) "",
 Logs: ([]string) {
 }
}
```

All int values are equal 0

**Comment by regcostajr** [comment]
#44
