### ISSUE TITLE
eth_signtransaction interface issue

### ISSUE THREAD

**Issue by junjchen** [regcostajr/go-web3#42]
As far as I can see `eth_signtransaction` is not mentioned  in JSON-RPC specification, though it does appear in parity JSON-RPC doc and seems it does work in geth as well.

Also there is `eth_sign` from JSON-RPC that has not been implemented.

What you guys think, do we wanna strictly follow the specification or we are fine with non standard api as well

**Comment by NatoliChris** [comment]
Yep, it looks like the ``eth_signtransaction`` exists but isn't documented on the public JSON-RPC specs. 

I think it would be good to provide it as an endpoint, it seems incredibly useful.

To standardise things, `Web3.js` [includes it](https://github.com/ethereum/web3.js/blob/6d3e61a010501011a107a79574cc7516900fa9e4/lib/web3/methods/eth.js#L205) , so I think it would be good to include it?

**Comment by junjchen** [comment]
Since there lacks a formal spec, small differences exist in vendor implementations on the API. For example parity allows optional nonce field [signer.rs](https://github.com/paritytech/parity/blob/8057e8df43e78328509c3a468592b8e798772f84/rpc/src/v1/impls/signer.rs#L132) while geth does not [api.go](https://github.com/ethereum/go-ethereum/blob/cbfb40b0aab093e1b612f3b16834894b2cc67882/internal/ethapi/api.go#L392).

But @NatoliChris I totally agree with you it is a handy tool to have. We can improve the documentation to make users aware of these nuances

**Comment by junjchen** [comment]
@NatoliChris think that's for another discussion, will close this issue now and have a new one opened =)
