### ISSUE TITLE
HTTP 405 - eth.SendTransaction

### ISSUE THREAD

**Issue by mbiamont** [regcostajr/go-web3#6]
Hi,
I've tried to use the function `eth.SendTransaction` but I reveive an HTTP 405 error code.

My code : 
```
const RopstenProvider = "ropsten.infura.io/metamask"
const BobAddress = "0xeeE7591A5fc3711A3415198841E27b3C3e4cF341"
const ContractAddress = "0x61eC19B1e1913698e91167AACDcC0ba6407559aC"

(...)

	web3Client := web3.NewWeb3(providers.NewHTTPProvider(RopstenProvider, 10, true))
	balance, err := web3Client.Eth.GetBalance(BobAddress, block.LATEST)

	if err != nil {
		panic(err)
	}

	realBalance := float64(balance.ToInt64()) / math.Pow10(18)

	fmt.Printf("Balance : %.3f\n", realBalance)
	
	transaction := new(dto.TransactionParameters)
	transaction.From = BobAddress
	transaction.To = ContractAddress
	transaction.Value = 1
	transaction.Gas = 75553
	transaction.GasPrice = 1

	resp, err := web3Client.Eth.SendTransaction(transaction)

	if err != nil {
		panic(err)
	}

	fmt.Printf("Response : %s\n", resp)
```

Maybe I'm doing something wrong here. Can you explain my error ?

**Comment by regcostajr** [comment]
I see that you using Infura, and they do not have support for the SendTransaction method:
https://github.com/INFURA/infura/wiki/FAQ

To send a transaction to Infura you will have to use the SendRawTransaction method and sign it locally, but the sendrawtransaction method is not yet implemented.

For now the solution is to have a node running.

**Comment by mbiamont** [comment]
OK, thanks for the info.
I'll try to implement the SendRawTransaction myself so.
