### ISSUE TITLE
constant 500000000000000000000 overflows types.ComplexIntParameter

### ISSUE THREAD

**Issue by chebykin** [regcostajr/go-web3#9]
I'm getting this error when trying to send for ex. 500 ETH:

```
txId, err := connection.Personal.SendTransaction(&dto.TransactionParameters{
    From:  me,
    To:    you,
    Value: 500 * 1000000000000000000,
}, "mypass")
```

**Comment by regcostajr** [comment]
Yep, we can't use int64 to transaction parameters

This PR will resolve this: https://github.com/regcostajr/go-web3/pull/10

You can use now:

import ```math/big```

```
big.NewInt(0).Mul(big.NewInt(500), big.NewInt(1E18))
```

or


```
new(big.Int).SetString("500000000000000000000",10)
```

**Comment by chebykin** [comment]
@regcostajr Thank you for so quick fix! It works now.
